pipeline {
    agent {
        label 'general_builder'
    }

    stages {
		stage ("Build") {
        	steps {
                dir('/var/jenkins_home/workspace/faketwitter/faketwitter') {
                    sh './gradlew clean build'
                }
            }
        }
        stage ('Build docker image') {
            steps {
                sh 'docker build -t pedro/faketwitter .'
            }
        }
        stage ('Deploy') {
            steps {
                sh 'docker run -d -p 3000:3000 pedro/faketwitter'
            }
        }
    }
}